apiVersion: batch/v1

kind: Job

metadata:
  name: mpioperator-openmpi-latest-demo1
  namespace: job-demo1

spec:
  template:
    spec:
      restartPolicy: Never

      schedulerName: yunikorn

      volumes:
      - name: code
        hostPath:
          path: /mnt/jobs/code
          type: Directory
      - name: env
        emptyDir: {}

      initContainers:
      - name: env-builder
        image: ubuntu:22.04
        command: ["/bin/bash","-c"]
        args:
          - |
            apt update && apt install -y python3 python3-pip git cmake build-essential wget curl  openmpi-bin  libssl-dev  build-essential  cmake  git  wget  curl 
            pip3 install  tensorflow  torch  xgboost  scikit-learn  ray  dask 

            cp -r /usr/local/* /env/ || true

        volumeMounts:
        - name: env
          mountPath: /env

      containers:
      - name: mpioperator-openmpi-latest
        image: mpioperator/openmpi:latest

        command: ["python3","/code/main.py"]
        volumeMounts:
        - name: code
          mountPath: /code
        - name: env
          mountPath: /usr/local

        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1

---
apiVersion: batch/v1

kind: Job

metadata:
  name: bitnami-spark-3-5-demo1
  namespace: job-demo1

spec:
  template:
    spec:
      restartPolicy: Never

      schedulerName: yunikorn


      containers:
      - name: bitnami-spark-3-5
        image: bitnami/spark:3.5


        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1

---
apiVersion: batch/v1

kind: Job

metadata:
  name: flink-1-18-demo1
  namespace: job-demo1

spec:
  template:
    spec:
      restartPolicy: Never

      schedulerName: yunikorn


      containers:
      - name: flink-1-18
        image: flink:1.18


        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1

---
apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: bitnami-kafka-3-6-1-demo1
  namespace: job-demo1

spec:
  serviceName: bitnami-kafka-3-6-1-demo1
  selector:
    matchLabels:
      app: bitnami-kafka-3-6-1-demo1
  template:
    metadata:
      labels:
        app: bitnami-kafka-3-6-1-demo1
    spec:

      schedulerName: yunikorn


      containers:
      - name: bitnami-kafka-3-6-1
        image: bitnami/kafka:3.6.1


        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1

---
apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: bitnami-hadoop-3-3-6-demo1
  namespace: job-demo1

spec:
  serviceName: bitnami-hadoop-3-3-6-demo1
  selector:
    matchLabels:
      app: bitnami-hadoop-3-3-6-demo1
  template:
    metadata:
      labels:
        app: bitnami-hadoop-3-3-6-demo1
    spec:

      schedulerName: yunikorn


      containers:
      - name: bitnami-hadoop-3-3-6
        image: bitnami/hadoop:3.3.6


        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1

---
apiVersion: batch/v1

kind: Job

metadata:
  name: tensorflow-tensorflow-2-15-0-gpu-demo1
  namespace: job-demo1

spec:
  template:
    spec:
      restartPolicy: Never

      schedulerName: yunikorn

      volumes:
      - name: code
        hostPath:
          path: /mnt/jobs/code
          type: Directory
      - name: env
        emptyDir: {}

      initContainers:
      - name: env-builder
        image: ubuntu:22.04
        command: ["/bin/bash","-c"]
        args:
          - |
            apt update && apt install -y python3 python3-pip git cmake build-essential wget curl  openmpi-bin  libssl-dev  build-essential  cmake  git  wget  curl 
            pip3 install  tensorflow  torch  xgboost  scikit-learn  ray  dask 

            cp -r /usr/local/* /env/ || true

        volumeMounts:
        - name: env
          mountPath: /env

      containers:
      - name: tensorflow-tensorflow-2-15-0-gpu
        image: tensorflow/tensorflow:2.15.0-gpu

        command: ["python3","/code/main.py"]
        volumeMounts:
        - name: code
          mountPath: /code
        - name: env
          mountPath: /usr/local

        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1

---
apiVersion: batch/v1

kind: Job

metadata:
  name: pytorch-pytorch-2-1-0-cuda11-8-cudnn8-runtime-demo1
  namespace: job-demo1

spec:
  template:
    spec:
      restartPolicy: Never

      schedulerName: yunikorn

      volumes:
      - name: code
        hostPath:
          path: /mnt/jobs/code
          type: Directory
      - name: env
        emptyDir: {}

      initContainers:
      - name: env-builder
        image: ubuntu:22.04
        command: ["/bin/bash","-c"]
        args:
          - |
            apt update && apt install -y python3 python3-pip git cmake build-essential wget curl  openmpi-bin  libssl-dev  build-essential  cmake  git  wget  curl 
            pip3 install  tensorflow  torch  xgboost  scikit-learn  ray  dask 

            cp -r /usr/local/* /env/ || true

        volumeMounts:
        - name: env
          mountPath: /env

      containers:
      - name: pytorch-pytorch-2-1-0-cuda11-8-cudnn8-runtime
        image: pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime

        command: ["python3","/code/main.py"]
        volumeMounts:
        - name: code
          mountPath: /code
        - name: env
          mountPath: /usr/local

        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu: 1
